import { defineConfig } from 'vite';
import path from 'node:path';
import fs from 'node:fs';

// Deployment target (established in the A3/V2 deployment investigation):
// Project Pages → https://nikunjnawal.github.io/CalcVerse-Pro/
// Assets must therefore be emitted relative to /CalcVerse-Pro/ in production
// builds, while dev/preview stay at root for local ergonomics.
const PROD_BASE = '/CalcVerse-Pro/';

// A3: page entries are generated by scripts/build-pages.mts (npm prebuild).
function generatedInputs(): Record<string, string> {
  const manifestPath = path.resolve(__dirname, '.generated/site.json');
  if (!fs.existsSync(manifestPath)) return {};
  const site = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as {
    pages: { name: string; file: string }[];
  };
  return Object.fromEntries(site.pages.map(p => [p.name, p.file]));
}

export default defineConfig(({ command }) => ({
  root: '.',
  base: command === 'build' ? PROD_BASE : '/',
  publicDir: 'public',
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
      '@calc-engine': path.resolve(__dirname, 'packages/calc-engine/src'),
      '@theme': path.resolve(__dirname, 'packages/theme/src'),
      '@ui': path.resolve(__dirname, 'packages/ui-components/src'),
      '@format': path.resolve(__dirname, 'packages/format/src'),
      '@quantities': path.resolve(__dirname, 'packages/quantities/src'),
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        index: 'index.html',
        ...generatedInputs(),
      },
    },
    target: 'ES2022',
    minify: 'esbuild',
  },
  server: {
    port: 3000,
    open: false,
  },
  css: {
    devSourcemap: true,
  },
}));
